//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace ShopEaseNew
{
    public partial class Home
    {
        /// <summary>
        /// btnExplore control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnExplore;

        /// <summary>
        /// btnDeals control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnDeals;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// Button1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button1;

        /// <summary>
        /// Button2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button2;

        /// <summary>
        /// Button3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button3;
    }
}